name: Update recently read book

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          BOOKLOG_USER_ID: ${{ secrets.BOOKLOG_USER_ID }} 